<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsWindows>false</IsWindows>
    <IsLinux>false</IsLinux>
    <IsOSX>false</IsOSX>
    <IsWSL>false</IsWSL>
    <IsWindows Condition="$([System.OperatingSystem]::IsWindows())">true</IsWindows>
    <IsLinux Condition="$([System.OperatingSystem]::IsLinux())">true</IsLinux>
    <IsOSX Condition="$([System.OperatingSystem]::IsMacOS())">true</IsOSX>
    <IsWSL Condition="'$(WSL_DISTRO_NAME)' != ''">true</IsWSL>
  </PropertyGroup>
  <!-- 在 .csproj 同级目录下创建 Local.props 手动指定自己的 RW 路径 -->
  <!--
  Local.props:
    <Project>
      <PropertyGroup>
        <RimWorldPath>path\to\rimworld</RimWorldPath>
      </PropertyGroup>
    </Project>
  -->
  <!-- 使用 Directory.Build.props 也行，内容跟上面的一样 -->
  <Import Project="Local.props" Condition="Exists('Local.props')"/>

  <!-- 如果没有，查找环境变量 RIMWORLD_DIR -->
  <PropertyGroup Condition=" '$(RimWorldPath)' == '' ">
    <RimWorldPath>$(RIMWORLD_DIR)</RimWorldPath>
  </PropertyGroup>

  <!-- 都没有，全平台兜底碰运气 -->
  <!-- https://learn.microsoft.com/zh-cn/visualstudio/msbuild/property-functions?view=vs-2022 -->
  <PropertyGroup Condition="'$(IsWindows)' == 'true'">
    <!-- 只能检测 Steam 安装所在盘的游戏，如果游戏安装在非 Steam 盘下，失效 -->
    <RegSteamPath>$(registry:HKEY_CURRENT_USER\Software\Valve\Steam@SteamPath)\steamapps</RegSteamPath>

    <SteamLibraryPath Condition="'$(SteamLibraryPath)' == '' and Exists('$(RegSteamPath)/common/RimWorld')">$(RegSteamPath)</SteamLibraryPath>

    <SteamLibraryPath Condition="'$(SteamLibraryPath)' == ''">C:/Program Files (x86)/Steam/steamapps</SteamLibraryPath>

    <RimWorldPath Condition="'$(RimWorldPath)' == ''">$(SteamLibraryPath)/common/RimWorld</RimWorldPath>
    <RimWorldManagedPath>$(RimWorldPath)/RimWorldWin64_Data/Managed</RimWorldManagedPath>
  </PropertyGroup>

  <!-- WSL 专用 -->
  <PropertyGroup Condition="'$(IsWSL)' == 'true'">
    <RimWorldPath Condition="'$(RimWorldPath)' == ''">/mnt/g/RimWorldMods/RimWorld</RimWorldPath>
    <RimWorldManagedPath>$(RimWorldPath)/RimWorldWin64_Data/Managed</RimWorldManagedPath>
  </PropertyGroup>

  <!-- Linux -->
  <PropertyGroup Condition="'$(IsLinux)' == 'true' and '$(IsWSL)' != 'true'">
    <RimWorldPath Condition="'$(RimWorldPath)' == ''">$(HOME)/.local/share/Steam/steamapps/common/RimWorld</RimWorldPath>
    <RimWorldManagedPath>$(RimWorldPath)/RimWorldLinux_Data/Managed</RimWorldManagedPath>
  </PropertyGroup>

  <!-- MacOS -->
  <PropertyGroup Condition="'$(IsOSX)' == 'true'">
    <RimWorldPath Condition="'$(RimWorldPath)' == ''">$(HOME)/Library/Application Support/Steam/steamapps/common/RimWorld</RimWorldPath>
    <RimWorldManagedPath>$(RimWorldPath)/Contents/Resources/Data/Managed</RimWorldManagedPath>
  </PropertyGroup>

  <!-- 我简直是太 TM 天才了，知道利用 Version.txt + 正则匹配游戏版本 -->
  <!-- 只希望其他平台也有这个文件 -->
  <PropertyGroup>
    <RimWorldVersionFile>$(RimWorldPath)/Version.txt</RimWorldVersionFile>
  </PropertyGroup>

  <PropertyGroup Condition="Exists('$(RimWorldVersionFile)')">
    <RawVersionContent>$([System.IO.File]::ReadAllText('$(RimWorldVersionFile)'))</RawVersionContent>
    <RimWorldVersion>$([System.Text.RegularExpressions.Regex]::Match($(RawVersionContent), '^\d+\.\d+'))</RimWorldVersion>
  </PropertyGroup>
  <!-- 兜底 -->
  <PropertyGroup Condition=" '$(RimWorldVersion)' == '' ">
    <RimWorldVersion>1.6</RimWorldVersion>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SD.GrayRace</RootNamespace>
    <AssemblyName>GrayRace</AssemblyName>
    <LangVersion>10</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Deterministic>false</Deterministic>

    <GenerateDependencyFile>false</GenerateDependencyFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>


  <PropertyGroup>
    <VerDay>$([System.DateTime]::Now.ToString("yyMM"))</VerDay>
    <VerTime>$([System.DateTime]::Now.ToString("ddHH"))</VerTime>

    <FullBuildDate>$([System.DateTime]::Now.ToString("yyyy-MM-dd"))</FullBuildDate>
    <Version>1.0.$(VerDay).$(VerTime)</Version>
    <InformationalVersion>$(Version) build at $(FullBuildDate)</InformationalVersion>
  </PropertyGroup>


  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\..\$(RimWorldVersion)\Assemblies\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\..\$(RimWorldVersion)\Assemblies\</OutputPath>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <!-- 别人的包可能会存在更新不及时的情况，尽可能引用游戏路径的 dll -->
  <ItemGroup>
    <Reference Include="$(RimWorldManagedPath)\Assembly-CSharp.dll" Private="False"/>
    <Reference Include="$(RimWorldManagedPath)\Unity*" Private="False"/>
  </ItemGroup>

  <ItemGroup>
    <!-- <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" /> -->
    <PackageReference Include="Lib.Harmony.Ref" Version="2.4.2"/>
  </ItemGroup>
</Project>
